version: '2'
services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer/data:/data

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - ./volumes/sonarr/data:/config
      - ./media/tvshows:/tv
      - ./downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:5.14
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Prague
    volumes:
      - ./volumes/radarr/config:/config
      - ./media/movies:/movies
      - ./downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ./volumes/jackett/config:/config
      - ./downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  plex:
    image: ghcr.io/linuxserver/plex:bionic
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    volumes:
      - ./volumes/plex/library:/config
      - ./media/tvshows:/tv
      - ./media/movies:/movies
    restart: unless-stopped

#  deluge:
#    image: linuxserver/deluge
#    container_name: deluge
#    # network_mode: host
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/Prague
#      - DELUGE_LOGLEVEL=error #optional
#    volumes:
#      - ./volumes/deluge/config:/config
#      - ./downloads:/downloads
#    ports:
#      - 8112:8112
#      - 58846:58846
#      - 58946:58946
#    restart: unless-stopped

  deluge:
    restart: always
    image: doggosrocko/arch-delugevpn-armhf
    container_name: deluge
    cap_add:
      - NET_ADMIN
    ports:
      - 8112:8112
      - 8118:8118
      - 58846:58846
      - 58945:58946
    volumes:
      - ./volumes/deluge/config:/config
      - ./downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=p
      - VPN_PASS=
      - VPN_PROV=pia
      - VPN_CLIENT=openvpn
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - VPN_INPUT_PORTS=1234
      - VPN_OUTPUT_PORTS=5678
      - DEBUG=false
      - PUID=1000
      - PGID=1000

  jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: unless-stopped
    user: 1000:1000
    volumes:
        - ./volumes/jdown/config:/opt/JDownloader/cfg
        - ./downloads:/opt/JDownloader/Downloads
        - ./volumes/jdown/logs:/opt/JDownloader/logs #optional
        - /etc/localtime:/etc/localtime:ro #optional
    environment: 
#            MYJD_USER:  #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
#            MYJD_PASSWORD:  #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
            MYJD_DEVICE_NAME: rpi4 #optional
            XDG_DOWNLOAD_DIR: /opt/JDownloader/Downloads #optional
    ports:
        - 3129:3129 

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - ./volumes/bazarr/config:/config
      - ./media/movies:/movies
      - ./media/tvshows:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./volumes/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
