version: '3.3'
services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROOT}/volumes/portainer/data:/data

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/volumes/sonarr/data:/config
      - ${DIR}:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/volumes/radarr/config:/config
      - ${DIR}:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ${ROOT}/volumes/jackett/config:/config
      - ${DIR}:/data
    ports:
      - 9117:9117
    restart: unless-stopped

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    volumes:
      - ${ROOT}/volumes/plex/library:/config
      - ${DIR}:/data
    restart: unless-stopped

  transmission-openvpn:
      container_name: transmission
      cap_add:
        - NET_ADMIN
      volumes:
        - ${ROOT}/volumes/transmission/config:/config
        - ${DIR}:/data
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - OPENVPN_PROVIDER=PIA
        - OPENVPN_CONFIG=czech_republic
        - OPENVPN_USERNAME=${PIAU}
        - OPENVPN_PASSWORD=${PIAP}
        - LOCAL_NETWORK=10.0.0.0/8,192.168.0.0/16
      ports:
        - 9091:9091
      image: haugene/transmission-openvpn
      restart: unless-stopped

  deluge:
    restart: always
    image: doggosrocko/arch-delugevpn-armhf
    container_name: deluge
    cap_add:
      - NET_ADMIN
    ports:
      - 8112:8112
      - 8118:8118
      - 58846:58846
      - 58945:58946
    volumes:
      - ${ROOT}/volumes/deluge/config:/config
      - /etc/localtime:/etc/localtime:ro
      - ${DIR}:/data
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=${PIAU}
      - VPN_PASS=${PIAP}
      - VPN_PROV=pia
      - VPN_CLIENT=openvpn
      - STRICT_PORT_FORWARD=yes
      - ENABLE_PRIVOXY=yes
      - LAN_NETWORK=10.12.0.0/24,192.168.1.0/24,10.42.42.0/24
      - NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - VPN_INPUT_PORTS=1234
      - VPN_OUTPUT_PORTS=5678
      - DEBUG=false
      - PUID=${PUID}
      - PGID=${PGID}

  
  jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: unless-stopped
    user: ${PGID}:${PUID}
    volumes:
        - /etc/localtime:/etc/localtime:ro #optional
        - ${ROOT}/volumes/jdown/config:/opt/JDownloader/cfg
        - ${ROOT}/volumes/jdown/logs:/opt/JDownloader/logs #optional
        - ${DIR}:/data
    environment: 
        - MYJD_USER=${JDUSR}  #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
        - MYJD_PASSWORD=${JDPASS}  #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
        - MYJD_DEVICE_NAME=rpi4 #optional
        - XDG_DOWNLOAD_DIR=/data/JDown #optional
    ports:
        - 3129:3129 

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/volumes/bazarr/config:/config
      - ${DIR}:/data
    ports:
      - 6767:6767
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/volumes/readar/config:/config
      - ${DIR}:/data
    ports:
      - 8787:8787
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/volumes/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
    volumes:
      - ${ROOT}/volumes/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  doublecommander:
    image: lscr.io/linuxserver/doublecommander
    container_name: doublecommander
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
    volumes:
      - ${ROOT}/volumes/doublecommander/config:/config
      - ${DIR}:/data
    ports:
      - 3000:3000
    restart: unless-stopped

  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
    volumes:
      - ${ROOT}/volumes/homeassistant:/config
    ports:
      - 8123:8123 #optional
#   devices: # passing device, eg. usb device
#      - /path/to/device:/path/to/device #optional
    restart: unless-stopped

  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - ${ROOT}/volumes/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host

  samba:
    image: dperson/samba:armhf
    container_name: samba
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ${DIR}:/data:z
    command: '-s "malina;/data;yes;no;yes;" -u "${SAMBAUSR};${SAMBAPASS}" -p' # malina should have access to anyone for anything
   #command: '-s "usbhub;/mnt" -s "Bobs Volume;/mnt2;yes;no;no;bob" -u "bob;bobspasswd"'
